### ISSUE TITLE
Creating Machine Learning Backend

### ISSUE THREAD

**Issue by ausaafnabi** [ausaafnabi/ML-OverRPC-API#1]
### **OBJECTIVE**
Creating Sample templates for different layers using Tensorflow and keras API.  Using the Over-RPC to call these templates systematically to create a complete sketch for the Machine Learning Model.

**TODO:**

- Adding Templates...

- Creating Logic for Over-RPC CLI to use these templates.

**Comment by ausaafnabi** [comment]
### **Templates Designing:**

- [x] Template for Imports the library based on preferences.....

- [x] Dataset Import Template

- [x] Data pre-processor for given backend Library. 

**Feature to include in next commit**
